// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Term                 uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaseLastSeenNew     *LeaseItem             `protobuf:"bytes,2,opt,name=lease_last_seen_new,json=leaseLastSeenNew,proto3" json:"lease_last_seen_new,omitempty"`
	LeaseLastSeenRevoked *LeaseItem             `protobuf:"bytes,3,opt,name=lease_last_seen_revoked,json=leaseLastSeenRevoked,proto3" json:"lease_last_seen_revoked,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TickRequest) Reset() {
	*x = TickRequest{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickRequest) ProtoMessage() {}

func (x *TickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickRequest.ProtoReflect.Descriptor instead.
func (*TickRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *TickRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *TickRequest) GetLeaseLastSeenNew() *LeaseItem {
	if x != nil {
		return x.LeaseLastSeenNew
	}
	return nil
}

func (x *TickRequest) GetLeaseLastSeenRevoked() *LeaseItem {
	if x != nil {
		return x.LeaseLastSeenRevoked
	}
	return nil
}

type TickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LeasesNew     []*LeaseItem           `protobuf:"bytes,2,rep,name=leases_new,json=leasesNew,proto3" json:"leases_new,omitempty"`
	LeasesRevoked []*LeaseItem           `protobuf:"bytes,3,rep,name=leases_revoked,json=leasesRevoked,proto3" json:"leases_revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickResponse) Reset() {
	*x = TickResponse{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickResponse) ProtoMessage() {}

func (x *TickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickResponse.ProtoReflect.Descriptor instead.
func (*TickResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *TickResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TickResponse) GetLeasesNew() []*LeaseItem {
	if x != nil {
		return x.LeasesNew
	}
	return nil
}

func (x *TickResponse) GetLeasesRevoked() []*LeaseItem {
	if x != nil {
		return x.LeasesRevoked
	}
	return nil
}

type LeaseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TTL           uint64                 `protobuf:"varint,2,opt,name=TTL,proto3" json:"TTL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseItem) Reset() {
	*x = LeaseItem{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseItem) ProtoMessage() {}

func (x *LeaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseItem.ProtoReflect.Descriptor instead.
func (*LeaseItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *LeaseItem) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *LeaseItem) GetTTL() uint64 {
	if x != nil {
		return x.TTL
	}
	return 0
}

type LeaseTickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LeasesNew     []*LeaseItem           `protobuf:"bytes,2,rep,name=leases_new,json=leasesNew,proto3" json:"leases_new,omitempty"`
	LeasesRevoked []*LeaseItem           `protobuf:"bytes,3,rep,name=leases_revoked,json=leasesRevoked,proto3" json:"leases_revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseTickRequest) Reset() {
	*x = LeaseTickRequest{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseTickRequest) ProtoMessage() {}

func (x *LeaseTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseTickRequest.ProtoReflect.Descriptor instead.
func (*LeaseTickRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

func (x *LeaseTickRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LeaseTickRequest) GetLeasesNew() []*LeaseItem {
	if x != nil {
		return x.LeasesNew
	}
	return nil
}

func (x *LeaseTickRequest) GetLeasesRevoked() []*LeaseItem {
	if x != nil {
		return x.LeasesRevoked
	}
	return nil
}

type LeaseTickResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Epoch                uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LeaseLastSeenNew     *LeaseItem             `protobuf:"bytes,2,opt,name=lease_last_seen_new,json=leaseLastSeenNew,proto3" json:"lease_last_seen_new,omitempty"`
	LeaseLastSeenRevoked *LeaseItem             `protobuf:"bytes,3,opt,name=lease_last_seen_revoked,json=leaseLastSeenRevoked,proto3" json:"lease_last_seen_revoked,omitempty"`
	LeasesExpired        []*LeaseItem           `protobuf:"bytes,4,rep,name=leases_expired,json=leasesExpired,proto3" json:"leases_expired,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LeaseTickResponse) Reset() {
	*x = LeaseTickResponse{}
	mi := &file_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseTickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseTickResponse) ProtoMessage() {}

func (x *LeaseTickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseTickResponse.ProtoReflect.Descriptor instead.
func (*LeaseTickResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{4}
}

func (x *LeaseTickResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *LeaseTickResponse) GetLeaseLastSeenNew() *LeaseItem {
	if x != nil {
		return x.LeaseLastSeenNew
	}
	return nil
}

func (x *LeaseTickResponse) GetLeaseLastSeenRevoked() *LeaseItem {
	if x != nil {
		return x.LeaseLastSeenRevoked
	}
	return nil
}

func (x *LeaseTickResponse) GetLeasesExpired() []*LeaseItem {
	if x != nil {
		return x.LeasesExpired
	}
	return nil
}

type TermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermRequest) Reset() {
	*x = TermRequest{}
	mi := &file_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermRequest) ProtoMessage() {}

func (x *TermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermRequest.ProtoReflect.Descriptor instead.
func (*TermRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{5}
}

func (x *TermRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type TermResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermResponse) Reset() {
	*x = TermResponse{}
	mi := &file_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermResponse) ProtoMessage() {}

func (x *TermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermResponse.ProtoReflect.Descriptor instead.
func (*TermResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{6}
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\fetcdserverpb\"\xb9\x01\n" +
	"\vTickRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12F\n" +
	"\x13lease_last_seen_new\x18\x02 \x01(\v2\x17.etcdserverpb.LeaseItemR\x10leaseLastSeenNew\x12N\n" +
	"\x17lease_last_seen_revoked\x18\x03 \x01(\v2\x17.etcdserverpb.LeaseItemR\x14leaseLastSeenRevoked\"\x9c\x01\n" +
	"\fTickResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x126\n" +
	"\n" +
	"leases_new\x18\x02 \x03(\v2\x17.etcdserverpb.LeaseItemR\tleasesNew\x12>\n" +
	"\x0eleases_revoked\x18\x03 \x03(\v2\x17.etcdserverpb.LeaseItemR\rleasesRevoked\"-\n" +
	"\tLeaseItem\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x10\n" +
	"\x03TTL\x18\x02 \x01(\x04R\x03TTL\"\xa0\x01\n" +
	"\x10LeaseTickRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x126\n" +
	"\n" +
	"leases_new\x18\x02 \x03(\v2\x17.etcdserverpb.LeaseItemR\tleasesNew\x12>\n" +
	"\x0eleases_revoked\x18\x03 \x03(\v2\x17.etcdserverpb.LeaseItemR\rleasesRevoked\"\x81\x02\n" +
	"\x11LeaseTickResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12F\n" +
	"\x13lease_last_seen_new\x18\x02 \x01(\v2\x17.etcdserverpb.LeaseItemR\x10leaseLastSeenNew\x12N\n" +
	"\x17lease_last_seen_revoked\x18\x03 \x01(\v2\x17.etcdserverpb.LeaseItemR\x14leaseLastSeenRevoked\x12>\n" +
	"\x0eleases_expired\x18\x04 \x03(\v2\x17.etcdserverpb.LeaseItemR\rleasesExpired\"!\n" +
	"\vTermRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\"\x0e\n" +
	"\fTermResponseB(Z&github.com/pantopic/turbokube/internalb\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_goTypes = []any{
	(*TickRequest)(nil),       // 0: etcdserverpb.TickRequest
	(*TickResponse)(nil),      // 1: etcdserverpb.TickResponse
	(*LeaseItem)(nil),         // 2: etcdserverpb.LeaseItem
	(*LeaseTickRequest)(nil),  // 3: etcdserverpb.LeaseTickRequest
	(*LeaseTickResponse)(nil), // 4: etcdserverpb.LeaseTickResponse
	(*TermRequest)(nil),       // 5: etcdserverpb.TermRequest
	(*TermResponse)(nil),      // 6: etcdserverpb.TermResponse
}
var file_internal_proto_depIdxs = []int32{
	2, // 0: etcdserverpb.TickRequest.lease_last_seen_new:type_name -> etcdserverpb.LeaseItem
	2, // 1: etcdserverpb.TickRequest.lease_last_seen_revoked:type_name -> etcdserverpb.LeaseItem
	2, // 2: etcdserverpb.TickResponse.leases_new:type_name -> etcdserverpb.LeaseItem
	2, // 3: etcdserverpb.TickResponse.leases_revoked:type_name -> etcdserverpb.LeaseItem
	2, // 4: etcdserverpb.LeaseTickRequest.leases_new:type_name -> etcdserverpb.LeaseItem
	2, // 5: etcdserverpb.LeaseTickRequest.leases_revoked:type_name -> etcdserverpb.LeaseItem
	2, // 6: etcdserverpb.LeaseTickResponse.lease_last_seen_new:type_name -> etcdserverpb.LeaseItem
	2, // 7: etcdserverpb.LeaseTickResponse.lease_last_seen_revoked:type_name -> etcdserverpb.LeaseItem
	2, // 8: etcdserverpb.LeaseTickResponse.leases_expired:type_name -> etcdserverpb.LeaseItem
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
